### ISSUE TITLE
import a renderer from the Jupter server installed extensions

### ISSUE THREAD

**Issue by box-turtle** [datalayer/jupyter-ui#278]
### Problem

I need to import some output renderers that are installed on the Jupyter server I am connecting to. 

Currently I am including the source in my app and importing it from a folder in my repo to include in the Notebook renders array.

But I would like to dynamically load it from the Jupyter server - don't know if this is possible

**Comment by echarles** [comment]
Hi @box-turtle The renderers is normally javascript. Are you meaning that you need a renderer packaged in a jupyter server extension?

**Comment by box-turtle** [comment]
Yeah - I think this a problem I need to solve in my userland code. 

My jupyter-react notebook is pointed at a server where a user may install a custom output renderer - so I might need to dynamically load that renderer. (they are used to accessing this server via jupyterlab hosted there, so once they installed the extension, the javascript would be installed automatically)

The API is clear how I need to add it once I get the code - so I think I'll close this issue. Thanks.

**Comment by echarles** [comment]
fyi the Notebook has a `renderers` prop (eg `renderers={[geojsonRenderer]}`) if you know in advance the renderer you need.

Otherwise, the JupyerLabApp component may help you to be closer for the full jupyterlab (eg https://github.com/datalayer/jupyter-ui/blob/main/packages/react/src/examples/JupyterLabHeadlessApp.tsx). Happy to explore how to make it fully compatible with your case.

We also support dynamic loading of ipywidgets (see https://github.com/datalayer/jupyter-ui/blob/bbc23789e48650d060539b85f89b592d0346502e/packages/react/src/jupyter/ipywidgets/lab/manager.ts#L244-L256) - there is some inspiration to take there.

**Comment by box-turtle** [comment]
Thanks Eric - I knew about the renderers prop. Digging into the
JupyterLabHeadlessApp now and that looks promising for my use case!
